/*
 * Risk scoring API
 * This is an API that provides whitebox risk scoring
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Offsets model module.
 * @module model/Offsets
 * @version 1.0
 */
export class Offsets {
  /**
   * Constructs a new <code>Offsets</code>.
   * Risk offsets
   * @alias module:model/Offsets
   * @class
   * @param combinedRiskOffset {Number} 
   * @param fraudRiskOffset {Number} 
   * @param lendingRiskOffset {Number} 
   * @param reputationRiskOffset {Number} 
   */
  constructor(combinedRiskOffset, fraudRiskOffset, lendingRiskOffset, reputationRiskOffset) {
    this.combinedRiskOffset = combinedRiskOffset;
    this.fraudRiskOffset = fraudRiskOffset;
    this.lendingRiskOffset = lendingRiskOffset;
    this.reputationRiskOffset = reputationRiskOffset;
  }

  /**
   * Constructs a <code>Offsets</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Offsets} obj Optional instance to populate.
   * @return {module:model/Offsets} The populated <code>Offsets</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Offsets();
      if (data.hasOwnProperty('combinedRiskOffset'))
        obj.combinedRiskOffset = ApiClient.convertToType(data['combinedRiskOffset'], 'Number');
      if (data.hasOwnProperty('fraudRiskOffset'))
        obj.fraudRiskOffset = ApiClient.convertToType(data['fraudRiskOffset'], 'Number');
      if (data.hasOwnProperty('lendingRiskOffset'))
        obj.lendingRiskOffset = ApiClient.convertToType(data['lendingRiskOffset'], 'Number');
      if (data.hasOwnProperty('reputationRiskOffset'))
        obj.reputationRiskOffset = ApiClient.convertToType(data['reputationRiskOffset'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} combinedRiskOffset
 */
Offsets.prototype.combinedRiskOffset = undefined;

/**
 * @member {Number} fraudRiskOffset
 */
Offsets.prototype.fraudRiskOffset = undefined;

/**
 * @member {Number} lendingRiskOffset
 */
Offsets.prototype.lendingRiskOffset = undefined;

/**
 * @member {Number} reputationRiskOffset
 */
Offsets.prototype.reputationRiskOffset = undefined;

