/*
 * Risk scoring API
 * This is an API that provides whitebox risk scoring
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RiskScores model module.
 * @module model/RiskScores
 * @version 1.0
 */
export class RiskScores {
  /**
   * Constructs a new <code>RiskScores</code>.
   * Risk score
   * @alias module:model/RiskScores
   * @class
   * @param combinedRisk {Number} 
   * @param fraudRisk {Number} 
   * @param lendingRisk {Number} 
   * @param reputationRisk {Number} 
   */
  constructor(combinedRisk, fraudRisk, lendingRisk, reputationRisk) {
    this.combinedRisk = combinedRisk;
    this.fraudRisk = fraudRisk;
    this.lendingRisk = lendingRisk;
    this.reputationRisk = reputationRisk;
  }

  /**
   * Constructs a <code>RiskScores</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RiskScores} obj Optional instance to populate.
   * @return {module:model/RiskScores} The populated <code>RiskScores</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RiskScores();
      if (data.hasOwnProperty('combinedRisk'))
        obj.combinedRisk = ApiClient.convertToType(data['combinedRisk'], 'Number');
      if (data.hasOwnProperty('fraudRisk'))
        obj.fraudRisk = ApiClient.convertToType(data['fraudRisk'], 'Number');
      if (data.hasOwnProperty('lendingRisk'))
        obj.lendingRisk = ApiClient.convertToType(data['lendingRisk'], 'Number');
      if (data.hasOwnProperty('reputationRisk'))
        obj.reputationRisk = ApiClient.convertToType(data['reputationRisk'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} combinedRisk
 */
RiskScores.prototype.combinedRisk = undefined;

/**
 * @member {Number} fraudRisk
 */
RiskScores.prototype.fraudRisk = undefined;

/**
 * @member {Number} lendingRisk
 */
RiskScores.prototype.lendingRisk = undefined;

/**
 * @member {Number} reputationRisk
 */
RiskScores.prototype.reputationRisk = undefined;

