/*
 * Risk scoring API
 * This is an API that provides whitebox risk scoring
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RiskScoringApi);
  }
}(this, function(expect, RiskScoringApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Offsets', function() {
      beforeEach(function() {
        instance = new RiskScoringApi.Offsets();
      });

      it('should create an instance of Offsets', function() {
        // TODO: update the code to test Offsets
        expect(instance).to.be.a(RiskScoringApi.Offsets);
      });

      it('should have the property combinedRiskOffset (base name: "combinedRiskOffset")', function() {
        // TODO: update the code to test the property combinedRiskOffset
        expect(instance).to.have.property('combinedRiskOffset');
        // expect(instance.combinedRiskOffset).to.be(expectedValueLiteral);
      });

      it('should have the property fraudRiskOffset (base name: "fraudRiskOffset")', function() {
        // TODO: update the code to test the property fraudRiskOffset
        expect(instance).to.have.property('fraudRiskOffset');
        // expect(instance.fraudRiskOffset).to.be(expectedValueLiteral);
      });

      it('should have the property lendingRiskOffset (base name: "lendingRiskOffset")', function() {
        // TODO: update the code to test the property lendingRiskOffset
        expect(instance).to.have.property('lendingRiskOffset');
        // expect(instance.lendingRiskOffset).to.be(expectedValueLiteral);
      });

      it('should have the property reputationRiskOffset (base name: "reputationRiskOffset")', function() {
        // TODO: update the code to test the property reputationRiskOffset
        expect(instance).to.have.property('reputationRiskOffset');
        // expect(instance.reputationRiskOffset).to.be(expectedValueLiteral);
      });

    });
  });

}));
