/*
 * Risk scoring API
 * This is an API that provides whitebox risk scoring
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RiskScoringApi);
  }
}(this, function(expect, RiskScoringApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('RiskScores', function() {
      beforeEach(function() {
        instance = new RiskScoringApi.RiskScores();
      });

      it('should create an instance of RiskScores', function() {
        // TODO: update the code to test RiskScores
        expect(instance).to.be.a(RiskScoringApi.RiskScores);
      });

      it('should have the property combinedRisk (base name: "combinedRisk")', function() {
        // TODO: update the code to test the property combinedRisk
        expect(instance).to.have.property('combinedRisk');
        // expect(instance.combinedRisk).to.be(expectedValueLiteral);
      });

      it('should have the property fraudRisk (base name: "fraudRisk")', function() {
        // TODO: update the code to test the property fraudRisk
        expect(instance).to.have.property('fraudRisk');
        // expect(instance.fraudRisk).to.be(expectedValueLiteral);
      });

      it('should have the property lendingRisk (base name: "lendingRisk")', function() {
        // TODO: update the code to test the property lendingRisk
        expect(instance).to.have.property('lendingRisk');
        // expect(instance.lendingRisk).to.be(expectedValueLiteral);
      });

      it('should have the property reputationRisk (base name: "reputationRisk")', function() {
        // TODO: update the code to test the property reputationRisk
        expect(instance).to.have.property('reputationRisk');
        // expect(instance.reputationRisk).to.be(expectedValueLiteral);
      });

    });
  });

}));
