/*
 * Risk scoring API
 * This is an API that provides whitebox risk scoring
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {Offsets} from './model/Offsets';
import {Reason} from './model/Reason';
import {RiskElaboration} from './model/RiskElaboration';
import {RiskReport} from './model/RiskReport';
import {RiskScores} from './model/RiskScores';
import {DefaultApi} from './api/DefaultApi';

/**
* This_is_an_API_that_provides_whitebox_risk_scoring.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var RiskScoringApi = require('index'); // See note below*.
* var xxxSvc = new RiskScoringApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new RiskScoringApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new RiskScoringApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new RiskScoringApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Offsets model constructor.
     * @property {module:model/Offsets}
     */
    Offsets,

    /**
     * The Reason model constructor.
     * @property {module:model/Reason}
     */
    Reason,

    /**
     * The RiskElaboration model constructor.
     * @property {module:model/RiskElaboration}
     */
    RiskElaboration,

    /**
     * The RiskReport model constructor.
     * @property {module:model/RiskReport}
     */
    RiskReport,

    /**
     * The RiskScores model constructor.
     * @property {module:model/RiskScores}
     */
    RiskScores,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
