/*
 * Risk scoring API
 * This is an API that provides whitebox risk scoring
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RiskScoringApi);
  }
}(this, function(expect, RiskScoringApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RiskScoringApi.DefaultApi();
  });

  describe('(package)', function() {
    describe('DefaultApi', function() {
      describe('scoreBtcAddressGet', function() {
        it('should call scoreBtcAddressGet successfully', function(done) {
          // TODO: uncomment, update parameter values for scoreBtcAddressGet call and complete the assertions
          /*

          instance.scoreBtcAddressGet(address, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(RiskScoringApi.RiskReport);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('scoreEthAddressGet', function() {
        it('should call scoreEthAddressGet successfully', function(done) {
          // TODO: uncomment, update parameter values for scoreEthAddressGet call and complete the assertions
          /*

          instance.scoreEthAddressGet(address, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(RiskScoringApi.RiskReport);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
